# Basic Rubocop configuration for Rails API project

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

# Style rules
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

# Layout rules
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics rules
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "app/controllers/api/v1/health_controller.rb"

Metrics/AbcSize:
  Max: 20

# Rails specific rules
Rails/SkipsModelValidations:
  Exclude:
    - "app/models/vaccination_record.rb"
    - "app/jobs/vaccination_expiration_job.rb"

Rails/Output:
  Exclude:
    - "db/seeds.rb"

# RSpec rules
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

# FactoryBot rules
FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

# Allow certain patterns
Naming/PredicateName:
  AllowedMethods:
    - has_expired_vaccinations?

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Lint/MissingSuper:
  Exclude:
    - "app/controllers/**/*"
    - "app/serializers/**/*"
