# Basic Rubocop configuration for Rails API project

plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

# Style rules
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

# Layout rules

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics rules
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "app/controllers/api/v1/health_controller.rb"

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "app/controllers/api/v1/pets_controller.rb"
    - "app/jobs/vaccination_expiration_job.rb"

# Rails specific rules
Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"
    - "app/models/vaccination_record.rb"
    - "app/jobs/vaccination_expiration_job.rb"

Rails/Output:
  Exclude:
    - "db/seeds.rb"

# Allow certain patterns
Naming/PredicatePrefix:
  AllowedMethods:
    - has_expired_vaccinations?
  Exclude:
    - "app/serializers/**/*"

Naming/PredicateMethod:
  Exclude:
    - "app/serializers/**/*"

# Allow empty else in jobs
Style/EmptyElse:
  Exclude:
    - "app/jobs/**/*"

# Allow longer lines in models for complex queries
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"
    - "app/models/**/*"

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Lint/MissingSuper:
  Exclude:
    - "app/controllers/**/*"
    - "app/serializers/**/*"
